Remove cpio patch 0001-Wrong-CRC-with-ASCII-CRC-for-large-files.patch
Remove the cpio CRC patch and .bbappend to fix error applying the same
patch twice.

Stefano's cpio patch has been duplicated and applied to the Yocto
poky/meta layer (master branch)  with this commit:

    commit c9f2486c527596a0c2657538a32de3fc3d43fe79
    Author: Marek Vasut <marex@denx.de>
    Date:   Wed Apr 5 23:33:58 2023 +0200

    cpio: Fix wrong CRC with ASCII CRC for large files

    Due to signedness, the checksum is not computed when filesize is bigger
    a 2GB. Pick a fix for this problem from CPIO ML, where the fix has been
    posted for 5 years. Since CPIO upstream is effectively unresponsive and
    any and all attempts to communicate with the maintainer and get the fix
    applied upstream failed, add the fix here instead.

    (From OE-Core rev: bfff138af4bdd356ac66571e6ad91c1a5599b935)

    Signed-off-by: Marek Vasut <marex@denx.de>
    Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Builds that include meta-swupdate have this error:

    ERROR: cpio-native-2.13-r0 do_patch: Applying patch '0001-Wrong-CRC-with-ASCII-CRC-for-large-files.patch'
    ... Patch 0001-Wrong-CRC-with-ASCII-CRC-for-large-files.patch is already applied; check your series file

Signed-off-by: Geoff Parker <geoffrey.parker@arthrex.com>