luafilesystem: upgrade to 1.8.0 to support lua 5.4
Yocto 4.0 (Kirkstone) ships Lua 5.4.4. This upgrade is required to fix
the following compiler error:

src/lfs.c:232:2: error: #error unsupported Lua version

Signed-off-by: Manuel Leonhardt <manuel@manuelleonhardt.de>