Add mtd-utils dependency if cfi or ubivol are set
This fixes the build issue below when CONFIG_CFI or CONFIG_UBIVOL are
set but CONFIG_MTD is not.

	| In file included from handlers/flash_handler.c:44:0:
	| include/flash.h:26:24: fatal error: mtd/libmtd.h: No such file or directory
	|  #include <mtd/libmtd.h>

Signed-off-by: Gaël PORTAY <gael.portay@savoirfairelinux.com>