Add missing RDEPENDS to the swupdate SDK
The SDK for a custom image is not able to compile full featured swupdate,
because some static libs and headers are missing (liblua.a, ..).

corelib/lua_interface.c:20:10: fatal error: lua.h: No such file or directory
   20 | #include "lua.h"
      |          ^~~~~~~

Using TOOLCHAIN_TARGET_TASK += "lua-staticdev" in a custom image recipe
has the overhead of figuring out, what libs are relevant to build
swupdate. For easier development / meta-layer integration let's add the
missing dependencies via packagegroup-core-standalone-sdk-target.

The libs are now implicit added to TOOLCHAIN_TARGET_TASK via:
populate_sdk_base:
    TOOLCHAIN_TARGET_TASK += "packagegroup-core-standalone-sdk-target"

Signed-off-by: Michael Glembotzki <Michael.Glembotzki@iris-sensing.com>
Reviewed-by: Stefano Babic <stefano.babic@swupdate.org>